### ISSUE TITLE
Other ideas:

### ISSUE THREAD

**Issue by MesaBlack** [violetfrost/violetfrost.github.io#3]
- a startup screen saying ifruit maps
- A type/voice search bar (for locations that have names, as well as general areas)
- A compass (when clicked/tapped, it straightens the direction to North)
- (temporary) textures on buildings
- transparent portions for glass portions of buildings
- directions using the mostly speculative roads, and some math
- transit Routes (Bus, Metromule)
- optional TTS for directions and info cards
- info cards about buildings and their inspirations

**Comment by violetfrost** [comment]
I love the idea of a startup screen and more iFruit style branding - thanks for all these! Definitely will look into all of them when I move this to a better host, for now it's tough since I have to do so much postprocessing to convert it into a fully static site for GH Pages😔

[it will stay open source when moved though, just not hosted on github :)]
